### PR TITLE
port disable_browser_ca_verification and disable_ca_verification patches up to 19.0.0

### PR DESCRIPTION
**Pull request by borntohonk**
updated to feature both disable_browser_ca_verification and disable_ca_verification patches for 18.0.0 and now 19.0.0

### CODE REVIEW

**Comment by hyrdoshi** [comment]
can you update it to 19.0?

**Comment by borntohonk** [comment]
> can you update it to 19.0?

https://github.com/borntohonk/Switch-Ghidra-Guides/blob/master/scripts/disable_ca_verification_patch.py
https://github.com/borntohonk/Switch-Ghidra-Guides/blob/master/scripts/disable_browser_ca_verification_patch.py

place 19.0.0 nca's in Switch-Ghidra-Guides/firmware

python -m pip install lz4
git clone https://github.com/borntohonk/Switch-Ghidra-Guides
cd Switch-Ghidra-Guides
python scripts/mariko_keygen.py
tools/hactoolnet-windows.exe -t switchfs firmware --title 0100000000000024 --exefsdir firmware/titleid/0100000000000024/exefs/
tools/hactoolnet-windows.exe -t switchfs firmware --title 0100000000000803 --romfsdir firmware/titleid/0100000000000803/romfs/
cp firmware/titleid/0100000000000803/romfs/nro/netfront/core_2/default/cfi_enabled/webkit_wkc.nro.lz4 webkit_wkc.nro.lz4
tools/hactool-windows.exe -t nso0 firmware/titleid/0100000000000024/exefs/main --uncompressed uncompressed_ssl.nso0
python scripts/disable_ca_verification_patch.py
python scripts/disable_browser_ca_verification_patch.py


do it yourself in the future with the resources provided, I just haven't bothered making a PR here as well, I made two python scripts to port the patches forward instantly.

@misson20000

**Comment by hyrdoshi** [comment]
ah thank you, i was not aware of this script😅

**Comment by Nekit99** [comment]
> > can you update it to 19.0?
> 
> https://github.com/borntohonk/Switch-Ghidra-Guides/blob/master/scripts/disable_ca_verification_patch.py https://github.com/borntohonk/Switch-Ghidra-Guides/blob/master/scripts/disable_browser_ca_verification_patch.py
> 
> place 19.0.0 nca's in Switch-Ghidra-Guides/firmware
> 
> python -m pip install lz4 git clone https://github.com/borntohonk/Switch-Ghidra-Guides cd Switch-Ghidra-Guides python scripts/mariko_keygen.py tools/hactoolnet-windows.exe -t switchfs firmware --title 0100000000000024 --exefsdir firmware/titleid/0100000000000024/exefs/ tools/hactoolnet-windows.exe -t switchfs firmware --title 0100000000000803 --romfsdir firmware/titleid/0100000000000803/romfs/ cp firmware/titleid/0100000000000803/romfs/nro/netfront/core_2/default/cfi_enabled/webkit_wkc.nro.lz4 webkit_wkc.nro.lz4 tools/hactool-windows.exe -t nso0 firmware/titleid/0100000000000024/exefs/main --uncompressed uncompressed_ssl.nso0 python scripts/disable_ca_verification_patch.py python scripts/disable_browser_ca_verification_patch.py
> 
> do it yourself in the future with the resources provided, I just haven't bothered making a PR here as well, I made two python scripts to port the patches forward instantly.
> 
> @misson20000

can you explain the new algorithm for debian?
mariko_keygen.py was deleted 3 days ago and this algorithm non working anymore

**Comment by borntohonk** [comment]
> can you explain the new algorithm for debian? mariko_keygen.py was deleted 3 days ago and this algorithm no longer works(
@Nekit99 
it ("mariko_keygen.py") was refactored to entirely python based script instead:
https://github.com/borntohonk/Switch-Ghidra-Guides/blob/master/scripts/aes_sample.py
(and is unrelated to this pull request/ and unrelated to this github repository)

the two scripts referenced above are valid for 19.0.0+

**Pull request closed without merging**
