### PR TITLE
port disable_ca_verification patch to 15.0.0

### PR DESCRIPTION
**Pull request by borntohonk**

### CODE REVIEW

**Comment by relm** [comment]
I can't seem to get your patch working on 15.0.0. When applied, I receive error code 2155-8035 on all SSL communication. 

You've verified it's working? Anyone else test it?

**Comment by borntohonk** [comment]
> I can't seem to get your patch working on 15.0.0. When applied, I receive error code 2155-8035 on all SSL communication.
> 
> You've verified it's working? Anyone else test it?

You know what this patch is supposed to do right...?

**Comment by relm** [comment]
well, yes. I used the previous patch successfully with 14.1.2.

I have my Switch traffic being sent to Charles Proxy, after applying the patch, no SSL traffic is hitting my proxy and I get the error code I mentioned above - 2155-8035.

Without the patch, the traffic reaches the proxy but gives an SSL handshake error which is expected.

**Comment by borntohonk** [comment]
> well, yes. I used the previous patch successfully with 14.1.2.
> 
> I have my Switch traffic being sent to Charles Proxy, after applying the patch, no SSL traffic is hitting my proxy and I get the error code I mentioned above - 2155-8035.
> 
> Without the patch, the traffic reaches the proxy but gives an SSL handshake error which is expected.

You can verify the offsets yourself with ghidra or idapro if you'd like, as the extent to what I've done is port a patch consistent with the 12.0.0, 13.0.0 and 14.0.0 versions this repository already has.

49 50 53 33 32 (ips32 magic)
(offset) - (length of patch) - (patch to be applied at offset)
00 12 64 9C - 00 01 - 0A
00 12 6D 54 - 00 02 - 11 00
00 12 6D 57 - 00 01 - 14
00 12 6D A8 - 00 04 - 08 00 80 52
45 45 4F 46 (EEOF magic)

**Comment by borntohonk** [comment]
@relm seems i've made an oopsie, it should be `00 12 6D 54 - 00 02 - 15 00`,

**Comment by InternalLoss** [comment]
Can also confirm this works - LGTM :)

**Comment by misson20000** [comment]
thanks, @borntohonk and all who tested!

**Pull request merged**
