### PR TITLE
add disable_browser_ca_verification for 13.2.1 and 15.0.0

### PR DESCRIPTION
**Pull request by borntohonk**
I decided to port 'disable_browser_ca_verification' to 15.0.0 also, and noticed that 13.2.1 was missing and added that too while at it.

### CODE REVIEW

**Comment by misson20000** [comment]
has anyone been able to test either of these patches?

**Comment by borntohonk** [comment]
for 12.0.0 (FA7EA8512C4FF7059F5D4101268FA4) which is already in the repository, which is used for reference in this instance;
mov,w8,#0x2 -> mov,w8,#0x0 (48 00 80 52 -> 08 00 80 52)
mov,w2,w20 -> mov,w2,wzr (e2 03 14 2a -> e2 03 1f 2a)

12 0 0_browser_ca


for 15.0.0 (BB231E297F8D66FEBC0FA492B522EBB4) it is:
mov,w8,#0x2 -> mov,w8,#0x0 (48 00 80 52 -> 08 00 80 52)
mov,w2,w21 -> mov,w2,wzr (e2 03 15 2a -> e2 03 1f 2a)


15 0 0_browser_ca

**Comment by InternalLoss** [comment]
Unable to test 13.2.1 - 15.0.0 tested (on 15.0.1, but I remember a 15.0.0 patch that worked on both), works just fine; LGTM <3

**Comment by borntohonk** [comment]
> Unable to test 13.2.1 - 15.0.0 tested (on 15.0.1, but I remember a 15.0.0 patch that worked on both), works just fine; LGTM <3

15.0.1 and 15.0.0 has the same FOSS web-browser binary, so the patch is the same for 15.0.0 and 15.0.01

**Pull request closed without merging**
